config/routes.rb
Rails.application.routes.draw do
  root 'users#new' # login/signup

  post '/signup', to: 'users#create' # creates a user

  get  '/leaderboard', to: 'pages#leaderboard' # leaderboard (static)

  get  '/game', to: 'games#new' # game page
  post '/game', to: 'games#create'

  # get '/document', to: redirect('/documents')
  get '/document', to: 'documents#new'
  get'/documents', to: 'documents#show'
  post '/document', to: 'documents#create'

  get    '/login',   to: 'sessions#new' # login page for a specific user
  post   '/login',   to: 'sessions#create' # create new session
  delete '/logout',  to: 'sessions#destroy' # destroy session

  resources :users
  resources :games
  resources :documents
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
#
class Document < ActiveRecord::Base
  validate :file_size_under_one_mb

  def initialize(params = {})
    @file = params.delete(:file)
    super
    if @file
      self.filename = sanitize_filename(@file.original_filename)
      self.content_type = @file.content_type
      self.file_contents = @file.read
    end
  end

  private

  def sanitize_filename(filename)
    File.basename(filename)
  end

  NUM_BYTES_IN_MEGABYTE = 1_048_576
  def file_size_under_one_mb
    errors.add(:file, 'File size cannot be over one megabyte.') if
    (@file.size.to_f / NUM_BYTES_IN_MEGABYTE) > 1
  end
end

app/models/game.rb
#
class Game < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
#
class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
#
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/documents_controller.rb
#
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show]

  def index
    @documents = Document.all
    respond_to do |f|
      f.html # index.html.erb
      f.xml  { render xml: @users}
      f.json { render json: @users}
    end
  end

  def show
    send_data(@document.file_contents,
              type: @document.content_type,
              filename: @document.filename)
  end

  def new
    @document = Document.new
  end

  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to documents_path, notice: 'Document was successfully created.' }
        format.json { render action: 'show', status: :created, location: @document }
      else
        format.html { render action: 'new' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_document
    @document = Document.find(params[:id])
  end

  # Only allow the white list through.
  def document_params
    params.require(:document).permit(:file)
  end
end

app/controllers/games_controller.rb
#
class GamesController < ApplicationController
  def show
    @game = Game.find(params[:user_id])
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      save_data @game
      redirect_to @game
    else
      render 'new'
    end
  end

  private

  def game_params
    params.require(:game).permit(:user_id, :scene, :inventory, :score, :time)
  end
end

app/controllers/pages_controller.rb
#
class PagesController < ApplicationController
  def login
  end

  def profile
  end

  def leaderboard
  end

  def game
  end
end

app/controllers/sessions_controller.rb
#
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination' # Error message!
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def login
  end

  def profile
  end

  def leaderboard
  end

  def game
  end
end

app/controllers/users_controller.rb
#
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show, :edit, :update]
  before_action :correct_user,   only: [:show, :edit, :update]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  # Before filters

  # Confirms a logged-in user.
  def logged_in_user
    redirect_to login_url unless logged_in?
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
#
module DocumentsHelper
end

app/helpers/pages_helper.rb
#
module PagesHelper
end

app/helpers/sessions_helper.rb
#
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def save_data(game)
    session[:scene] = game.scene
    session[:inventory] = game.inventory
    session[:score] = game.score
    session[:time] = game.time
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Returns the current logged-in user (if any).
  def current_user
    if @current_user.nil?
      @current_user = User.find_by(id: session[:user_id])
    else
      @current_user
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
#
module UsersHelper
end

app/views/documents/index.html.haml
%section#login-page
  .form-wrap
    .tabs
      %h3.signup-tab
        %a.active{:id =>"signup-tab-content"} Add Content
      %h3.login-tab
        %a{:id => "login-tab-content"} View Content
    .tabs-content
      #signup-tab-content.active
        .signup-form
        -# = form_for(@document) do |f|
        -#   = f.file_field :file
        -# .actions
        -#   = f.submit
      #login-tab-content
        .login-form
        - @documents.each do |document|
          = document.filename
          = button_to 'Download', document, method: :get

app/views/documents/new.html.haml
%section#login-page
  .form-wrap
    .tabs
      %h3.signup-tab
        %a.active{:id =>"signup-tab-content"} Add Content
      %h3.login-tab
        %a{:id => "login-tab-content"} View Content
    .tabs-content
      #signup-tab-content.active
        .signup-form
        -# = form_for(@document) do |f|
        -#   = f.file_field :file
        -#   = f.submit
      #login-tab-content.active
        .login-form
          -# - @documents.each do |document|
          -#   = document.filename
          -#   = button_to 'Download', document, method: :get

app/views/games/new.html.haml
-# !!! 5
-# %html(lang='en')
-#   %head
-#     %meta(charset='UTF-8')
-#     %meta(content="width=device-width, initial-scale=1" name="viewport")
-#     %title Harry Potter Quest
%body
  %audio#potter-theme(loop autoplay src = "#{asset_path "pottertheme.mp3"}")
  %main
    %section.game-page
      .game-container
        %header.menu
          %ul.options
            %li.fileOption.option
              File
              %ul.fileOptions
                %li.save Save
                %li.restore Restore
            %li.invOption.option Inventory
            %li.scoreOption.option
              Score:
              %span.score 0
              &nbsp;of 30
            %li.timeOption.option Time:
        %button(class='startBtn') Play Game
        .typing
        .dialog Answer
        .inventoryContainer
          .inventoryTitle Inventory<br><br>
          .inventory
      .save-game-form
        =form_for(@game) do |f|
          =f.text_field :user_id, class: "saveUserId", value: session[:user_id]
          =f.text_field :scene, class: "saveScene", value: 'init'
          =f.text_field :inventory, class: "saveInventory", value: ''
          =f.text_field :score, class: "saveScore", value: 0
          =f.text_field :time, class: "saveTime", value: 0
          =f.submit "Save Game", class: "saveBtn"

      .current
        .savedId
          = session[:user_id]
        .savedScene
          = session[:scene]
        .savedInv
          = session[:inventory]
        .savedScore
          = session[:score]
        .savedTime
          = session[:time]


  =javascript_include_tag "vendor.min"
  =javascript_include_tag "game"

app/views/layouts/_header.html.haml
%header.nav-bar
  %ul
    %li.option= link_to "Profile", current_user
    %li.option= link_to "Game", game_path
    %li.option= link_to "Leaderboard", leaderboard_path
    %li.option= link_to "Contribute", new_document_path
    %li.option= link_to "Logout", logout_path, method: :delete
    %li.show-hide
      .nav-icon
        %a
          %i.material-icons menu

=javascript_include_tag "vendor.min"
=javascript_include_tag "nav"

app/views/layouts/_rails_default.html.haml
= csrf_meta_tags
= stylesheet_link_tag    'application', media: 'all', |
  'data-turbolinks-track': 'reload'                   |
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    = render 'layouts/rails_default'
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      = yield

app/views/pages/game.html.haml
-# !!! 5
-# %html(lang='en')
-#   %head
-#     %meta(charset='UTF-8')
-#     %meta(content="width=device-width, initial-scale=1" name="viewport")
-#     %title Harry Potter Quest
%body
  %audio#potter-theme(loop autoplay src = "#{asset_path "pottertheme.mp3"}")
  %main
    %section
      .game-container
        %header.menu
          %ul.options
            %li.fileOption.option
              File
              %ul.fileOptions
                %li.save Save
                %li.restore Restore
            %li.invOption.option Inventory
            %li.scoreOption.option
              Score:
              %span.score 0
              &nbsp;of 20
            %li.timeOption.option Time:
        %button(class='startBtn') Play Game
        .typing
        .dialog Answer
        .inventory

  -# .save-game-form
  -#   =form_for(@game) do |f|
  -#     =f.text_field :user_id, class: "saveUserId",
  -#     =f.text_field :scene, class: "saveScene",
  -#     =f.text_field :inventory, class: "saveInventory",
  -#     =f.text_field :score, class: "saveScore",
  -#     =f.text_field :time, class: "saveTime",
  -#     =f.submit "Save Game", class: "saveButton"

  =javascript_include_tag "vendor.min"
  =javascript_include_tag "game"

app/views/pages/leaderboard.html.haml
!!! 5
%html(lang='en')
  %section#leaderboard-page


=javascript_include_tag "vendor.min"
=javascript_include_tag "leaderboard"

app/views/shared/_error_messages.html.haml
- if @user.errors.any?
  #error_explanation
    .alert.alert-danger
      The form contains #{pluralize(@user.errors.count, "error")}.
    %ul
      - @user.errors.full_messages.each do |msg|
        %li= msg

app/views/users/new.html.haml
%section#login-page
  .form-wrap
    .tabs
      %h3.signup-tab
        %a.active{:id =>"signup-tab-content"} Sign Up
      %h3.login-tab
        %a{:id => "login-tab-content"} Login
    .tabs-content
      #signup-tab-content.active
        .signup-form
          =form_for(@user) do |f|
            =f.text_field :name, class: "input", placeholder: "Name"
            =f.email_field :email, class: "input", placeholder: "Email"
            -# =f.select_tag( :house, options_for_select([['Gryffindor', 'gryffindor_crest'], ['Ravenclaw', 'ravenclaw_crest']]))
            =f.password_field :password, class: "input", placeholder: "Password"
            =f.submit "Sign Up", class: "button"
          .snitch-container
            %img.snitch{:src => asset_path("golden_snitch.gif")}
      #login-tab-content
        .login-form
          =form_for(:session, url: login_path) do |f|
            =f.email_field :email, class: "input", placeholder: "Email"
            =f.password_field :password, class: "input", placeholder: "Password"
            =f.submit "Login", class: "button"
        .snitch-container
          %img.snitch{:src => asset_path("golden_snitch.gif")}

=javascript_include_tag "vendor.min"
=javascript_include_tag "login"

app/views/users/profile.html.haml
!!! 5
%section#profile-page
  .profile-wrap
    .tabs
      %h3.profile-tab
        %a.active{:id =>"profile-tab-content"} Profile
      %h3.games-tab
        %a{:id => "games-tab-content"} Games
      %h3.account-tab
        %a{:id => "account-tab-content"} Account
    .tabs-content
      #profile-tab-content.active
        %h3
          = @user.name
        %h3
          = @user.email


      #games-tab-content
      #account-tab-content


=javascript_include_tag "vendor.min"
=javascript_include_tag "profile"

app/views/users/show.html.haml
!!! 5
%section#profile-page
  .profile-wrap
    .tabs
      %h3.profile-tab
        %a.active{:id =>"profile-tab-content"} Profile
      %h3.game-stats-tab
        %a{:id => "game-stats-tab-content"} Game Stats
      %h3.account-tab
        %a{:id => "account-tab-content"} Account
    .tabs-content
      #profile-tab-content.active
        .content-text
          .title-container
            %h3 Name:
          .info-container
            %p
              = @user.name
          .title-container
            %h3 House:
          .info-container
            %p
              = @user.house
            %p Gryffindor
        .content-image
          %img.house-crest{:src => asset_path("gryffindor_crest.png")}

      #game-stats-tab-content
        .content-text
          .title-container
            %h3 Current Score:
          .info-container
            %p 0
          .title-container
            %h3 Current Level:
          .info-container
            %p Level 1
          .title-container
            %h3 Horcruxes Found:
          .info-container
            %p None yet. Keep searching!
        .content-image
          %img.flags{:src => asset_path("flags.png")}

      #account-tab-content
        .content-text
          .title-container
            %h3 Name:
          .info-container
            %p
              = @user.name
          .title-container
            %h3 Email:
          .info-container
            %p
              = @user.email
        .content-image



=javascript_include_tag "vendor.min"
=javascript_include_tag "profile"